In [1]:
import torch
import torch.nn as nn

In [2]:
test = torch.Tensor([[1,2,3],[4,5,6]])
test

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [5]:
test.shape

torch.Size([2, 3])

In [6]:
test2 = torch.reshape(test,(3,2))
test2

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [7]:
test.transpose(-1,-2)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])